// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Generates buy/sell signals for a given stock based on technical and fundamental analysis.
 *
 * - generateBuySellSignals - A function that generates buy/sell signals for a stock.
 * - GenerateBuySellSignalsInput - The input type for the generateBuySellSignals function.
 * - GenerateBuySellSignalsOutput - The return type for the generateBuySellSignals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBuySellSignalsInputSchema = z.object({
  ticker: z.string().describe('The ticker symbol of the stock.'),
  technicalAnalysis: z.string().describe('The technical analysis of the stock.'),
  fundamentalAnalysis: z.string().describe('The fundamental analysis of the stock.'),
});
export type GenerateBuySellSignalsInput = z.infer<typeof GenerateBuySellSignalsInputSchema>;

const GenerateBuySellSignalsOutputSchema = z.object({
  signal: z.enum(['Buy', 'Hold', 'Sell']).describe('The buy/sell signal for the stock.'),
  reason: z.string().describe('The reason for the buy/sell signal.'),
});
export type GenerateBuySellSignalsOutput = z.infer<typeof GenerateBuySellSignalsOutputSchema>;

export async function generateBuySellSignals(input: GenerateBuySellSignalsInput): Promise<GenerateBuySellSignalsOutput> {
  return generateBuySellSignalsFlow(input);
}

const analyzeNews = ai.defineTool(
  {
    name: 'analyzeNews',
    description: 'Analyzes recent news articles to determine their impact on a stock.',
    inputSchema: z.object({
      ticker: z.string().describe('The ticker symbol of the stock.'),
    }),
    outputSchema: z.string(),
  },
  async (input) => {
    // Placeholder implementation - replace with actual news analysis logic
    return `News analysis for ${input.ticker}: No significant news found.`;
  }
);

const prompt = ai.definePrompt({
  name: 'generateBuySellSignalsPrompt',
  input: {schema: GenerateBuySellSignalsInputSchema},
  output: {schema: GenerateBuySellSignalsOutputSchema},
  tools: [analyzeNews],
  system: `You are an expert financial analyst. Based on the technical analysis, fundamental analysis, and recent news, provide a buy/sell signal for the given stock.

Consider the following:
- Technical Analysis: {{{technicalAnalysis}}}
- Fundamental Analysis: {{{fundamentalAnalysis}}}

Use the analyzeNews tool to check for recent news related to the stock. Incorporate any relevant news into your recommendation.`,
  prompt: `Given the above analysis, what is your buy/sell signal for ${'{{{ticker}}}'}? Explain your reasoning.`, // Changed ticker reference to Handlebars syntax
});

const generateBuySellSignalsFlow = ai.defineFlow(
  {
    name: 'generateBuySellSignalsFlow',
    inputSchema: GenerateBuySellSignalsInputSchema,
    outputSchema: GenerateBuySellSignalsOutputSchema,
  },
  async input => {
    const newsAnalysis = await analyzeNews({ticker: input.ticker});
    const {output} = await prompt({...input, newsAnalysis});
    return output!;
  }
);
